// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package partials

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Header() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div><nav class=\"bg-white dark:bg-gray-800  shadow \"><div class=\"px-8 mx-auto max-w-7xl\"><div class=\"flex items-center justify-between h-16\"><div class=\"w-full justify-center md:justify-between flex flex-col md:flex-row items-center md:items-center\"><a class=\"flex-shrink-0 text-white text-lg\" href=\"/\">GoTodo App <span id=\"h-title\">.</span></a><div class=\"block\"><div class=\"flex items-baseline ml-10 space-x-4\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.RenderScriptItems(ctx, templ_7745c5c3_Buffer, changeTitle("todo"))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<a id=\"todo-link\" class=\"text-gray-800 cursor-pointer dark:text-white  hover:text-gray-800 dark:hover:text-white px-3 py-2 rounded-md text-sm font-medium\" onclick=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 templ.ComponentScript = changeTitle("todo")
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2.Call)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" hx-get=\"/todo\" hx-trigger=\"click\" hx-target=\"#main-content\" hx-update=\"#h-title\">TODOs</a> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.RenderScriptItems(ctx, templ_7745c5c3_Buffer, changeTitle("profile"))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<a onclick=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 templ.ComponentScript = changeTitle("profile")
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3.Call)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" class=\"text-gray-800 cursor-pointer dark:text-white  hover:text-gray-800 dark:hover:text-white px-3 py-2 rounded-md text-sm font-medium\" id=\"profile-link\" hx-get=\"/profile\" hx-trigger=\"click\" hx-target=\"#main-content\" hx-update=\"#h-title\">Profile</a></div></div></div></div></div></nav></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

func changeTitle(title string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_changeTitle_1d13`,
		Function: `function __templ_changeTitle_1d13(title){let todo = document.getElementById("todo-link");
	let profile = document.getElementById("profile-link");

	if (title == "todo") {
		profile.className = "text-gray-800 cursor-pointer dark:text-white  hover:text-gray-800 dark:hover:text-white px-3 py-2 rounded-md text-sm font-medium";
		todo.className = "text-blue-500 cursor-pointer hover:text-blue-800 dark:hover:text-white px-3 py-2 rounded-md text-sm font-medium";
	} else if(title == "profile") {
		todo.className = "text-gray-800 cursor-pointer dark:text-white  hover:text-gray-800 dark:hover:text-white px-3 py-2 rounded-md text-sm font-medium";
		profile.className = "text-blue-500 cursor-pointer hover:text-blue-800 dark:hover:text-white px-3 py-2 rounded-md text-sm font-medium";
	}

}`,
		Call:       templ.SafeScript(`__templ_changeTitle_1d13`, title),
		CallInline: templ.SafeScriptInline(`__templ_changeTitle_1d13`, title),
	}
}
